[project]
name = "test-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.3",
    "numpy>=2.1.3",
    "pydub>=0.25.1",
    "scipy>=1.14.1",
    "streamlit>=1.40.2",
]
